#ifndef __PROTOCOL_SESSION_H__
#define __PROTOCOL_SESSION_H__

#define SESSION_COMPONENTID			1

#define SESSION_AUTHREQUEST			1
#define SESSION_AUTHRESPONSE_OK			2
#define SESSION_AUTHRESPONSE_NOK_BADAUTH	3
#define SESSION_AUTHRESPONSE_NOK_DUPLICATE	4
#define	SESSION_DISCONNECT			5
#define SESSION_DISCONNECTED			6
#define SESSION_TIMEOUT				7
#define	SESSION_KEEPALIVE			8

#endif // ! __PROTOCOL_SESSION_H__
