#ifndef __PROTOCOL_CHANNEL_H__
#define __PROTOCOL_CHANNEL_H__

#define CHANNEL_COMPONENTID		2

#define CHANNEL_JOIN			1
#define CHANNEL_JOIN_OK			2
#define CHANNEL_JOIN_NOK_ALREADYINCHAN	3

#define CHANNEL_JOINED			4
#define CHANNEL_JOINED_ACK		5

#define CHANNEL_MESSAGE			6
#define CHANNEL_MESSAGE_ACK		7
#define CHANNEL_MESSAGE_RECV		8
#define CHANNEL_MESSAGE_RECV_ACK	9

#define CHANNEL_LEAVE			10
#define CHANNEL_LEAVE_OK		11
#define CHANNEL_LEAVE_NOK_NOTINCHAN	12

#define CHANNEL_LEAVED			13
#define CHANNEL_LEAVED_ACK		14

#endif // ! __PROTOCOL_CHANNEL_H__
