#ifndef __PROTOCOL_USERINFO_H__
#define __PROTOCOL_USERINFO_H__

#include <Protocol.h>

#define USERINFO_COMPONENTID				6

#define USERINFO_GETINFO_REQUEST			1
#define USERINFO_GETINFO_RESPONSE_OK			2
#define USERINFO_GETINFO_RESPONSE_NOK_INVALIDUSER	3
#define USERINFO_GETAVATAR_REQUEST			4
#define USERINFO_GETAVATAR_RESPONSE_OK			5
#define USERINFO_GETAVATAR_RESPONSE_NOK_INVALIDUSER	6

// binary data contained in packet in order of placement in the binary fields
#define PROTOV1_USERINFO_CLIENTSESSIONID_OFF	PROTOV1_START_OF_DATA * 8
#define PROTOV1_USERINFO_CLIENTSESSIONID_SIZE	PROTOV1_SESSIONID_SIZE

// data contained in packet in order of placement in the data fields
#define PROTOV1_USERINFO_START_OF_DATA		(PROTOV1_START_OF_DATA + BINARYTOBYTE_LEN(PROTOV1_USERINFO_CLIENTSESSIONID_OFF + PROTOV1_USERINFO_CLIENTSESSIONID_SIZE))

#define PROTOV1_USERINFO_DATA_USERINFO		0
#define PROTOV1_USERINFO_DATA_AVATAR		0

#endif // ! __PROTOCOL_USERINFO_H__
